name: Digital Ocean Deploy

env:
    NODE_ENV: production

on:
    push:
        branches: [master]

jobs:
    deploy:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sewquence of tasks that will be executed as part of the job
        steps:
            - name: SSH Remote Commands
                uses: appleboy/ssh-action@master
                with:
                    HOST: ${{ secrets.HOST }}
                    USERNAME: ${{ secrets.USERNAME }}
                    KEY: ${{ secrets.KEY }}
                    script: |
                        cd /root/Ferris
                        git pull
                        pm2 restart all
